import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Plus, Trash2, Check, AlertCircle, RotateCcw } from 'lucide-react';
import StatusBadge from '../../components/StatusBadge';
import { journalEntriesApi, journalsApi, accountsApi, contactsApi } from '../../api';
import { formatCurrency } from '../../utils/currency';
import { useDebitCreditBalance } from '../../hooks/useDebitCreditBalance';
import { usePermission } from '../../hooks/usePermission';

const today = () => new Date().toISOString().split('T')[0];

export default function JournalEntryForm() {
  const { id } = useParams();
  const isNew = !id || id === 'new';
  const navigate = useNavigate();
  const { isAdmin } = usePermission();
  const [accounts, setAccounts] = useState([]);
  const [journals, setJournals] = useState([]);
  const [contacts, setContacts] = useState([]);
  const [entry, setEntry] = useState(null);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ journalId: '', accountingDate: today(), reference: '', partnerId: '' });
  const { lines, setLines, totals, addLine, updateLine, removeLine } = useDebitCreditBalance([]);

  useEffect(() => {
    Promise.all([accountsApi.getAll(), journalsApi.getAll(), contactsApi.getAll()]).then(([a, j, c]) => { setAccounts(a); setJournals(j); setContacts(c); });
    if (!isNew) {
      journalEntriesApi.getById(id).then(e => {
        if (!e) return;
        setEntry(e);
        setForm({ journalId: e.journalId, accountingDate: e.accountingDate.split('T')[0], reference: e.reference || '', partnerId: e.partnerId || '' });
        setLines((e.items || []).map(i => ({ id: i.id, accountId: i.accountId, debit: i.debit, credit: i.credit })));
      });
    }
  }, [id, isNew]);

  const isAutoGenerated = entry && (entry.billId || entry.invoiceId);
  const isReadOnly = !isNew && (entry?.status === 'POSTED' || isAutoGenerated);

  const buildPayload = () => ({
    journalId: parseInt(form.journalId),
    accountingDate: form.accountingDate,
    reference: form.reference || null,
    partnerId: form.partnerId ? parseInt(form.partnerId) : null,
    items: lines.map(l => ({ accountId: parseInt(l.accountId), debit: parseFloat(l.debit) || 0, credit: parseFloat(l.credit) || 0 })),
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    try {
      if (isNew) {
        const created = await journalEntriesApi.create(buildPayload());
        navigate(`/accounting/entries/${created.id}`);
      } else {
        await journalEntriesApi.update(id, buildPayload());
        navigate('/accounting/entries');
      }
    } catch (err) {
      setError(err.message || 'Could not save entry');
    }
  };

  const handlePost = async () => {
    setError('');
    try {
      if (isNew) {
        const created = await journalEntriesApi.create(buildPayload());
        await journalEntriesApi.post(created.id);
      } else {
        await journalEntriesApi.update(id, buildPayload());
        await journalEntriesApi.post(id);
      }
      navigate('/accounting/entries');
    } catch (err) {
      setError(err.message || 'Could not post entry');
    }
  };

  const handleReset = async () => {
    try { await journalEntriesApi.reset(id); navigate('/accounting/entries'); } catch (err) { setError(err.message || 'Could not reset entry'); }
  };

  return (
    <>
      <div className="page-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)' }}>
          <button className="btn btn-ghost btn-icon" onClick={() => navigate('/accounting/entries')}><ArrowLeft size={20} /></button>
          <h1>{isNew ? 'New Journal Entry' : `Entry JE-${id}`}</h1>
          {entry && <StatusBadge status={entry.status} />}
        </div>
        {!isNew && entry?.status === 'POSTED' && !isAutoGenerated && isAdmin && (
          <div className="page-header-actions">
            <button className="btn btn-secondary" onClick={handleReset}><RotateCcw size={16} /> Reset to Draft</button>
          </div>
        )}
      </div>

      {error && <div className="form-error" role="alert">{error}</div>}

      {/* Balance Bar */}
      <div className="je-balance-bar">
        <div className="je-balance-item"><span className="je-balance-label">Total Debit:</span><span className="je-balance-value">{formatCurrency(totals.totalDebit)}</span></div>
        <div className="je-balance-item"><span className="je-balance-label">Total Credit:</span><span className="je-balance-value">{formatCurrency(totals.totalCredit)}</span></div>
        <div className={`je-balance-item ${totals.isBalanced ? 'balanced' : 'unbalanced'}`}>
          {totals.isBalanced ? <Check size={16} /> : <AlertCircle size={16} />}
          <span className="je-balance-label">Difference:</span>
          <span className="je-balance-value">{formatCurrency(Math.abs(totals.difference))}</span>
        </div>
      </div>

      <div className="card"><div className="card-body">
        <form onSubmit={handleSubmit}>
          <div className="form-row">
            <div className="form-group"><label className="form-label">Journal</label>
              <select className="form-select" value={form.journalId} onChange={e => setForm(f => ({ ...f, journalId: e.target.value }))} disabled={isReadOnly} required>
                <option value="">Select journal</option>
                {journals.map(j => <option key={j.id} value={j.id}>{j.name}</option>)}
              </select>
            </div>
            <div className="form-group"><label className="form-label">Date</label><input type="date" className="form-input" value={form.accountingDate} onChange={e => setForm(f => ({ ...f, accountingDate: e.target.value }))} disabled={isReadOnly} /></div>
            <div className="form-group"><label className="form-label">Reference</label><input className="form-input" value={form.reference} onChange={e => setForm(f => ({ ...f, reference: e.target.value }))} disabled={isReadOnly} /></div>
            <div className="form-group"><label className="form-label">Partner</label>
              <select className="form-select" value={form.partnerId} onChange={e => setForm(f => ({ ...f, partnerId: e.target.value }))} disabled={isReadOnly}>
                <option value="">None</option>
                {contacts.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
            </div>
          </div>

          <h3 style={{ margin: 'var(--space-4) 0 var(--space-3)' }}>Journal Items</h3>
          <div className="data-table-wrapper">
            <table className="line-item-table">
              <thead><tr><th>Account</th><th style={{ textAlign: 'right' }}>Debit</th><th style={{ textAlign: 'right' }}>Credit</th>{!isReadOnly && <th></th>}</tr></thead>
              <tbody>
                {lines.map(line => (
                  <tr key={line.id}>
                    <td><select value={line.accountId || ''} onChange={e => updateLine(line.id, 'accountId', e.target.value)} disabled={isReadOnly}>
                      <option value="">Select account</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name} ({a.type})</option>)}
                    </select></td>
                    <td><input type="number" min="0" step="0.01" value={line.debit || ''} onChange={e => updateLine(line.id, 'debit', parseFloat(e.target.value) || 0)} style={{ textAlign: 'right' }} disabled={isReadOnly} /></td>
                    <td><input type="number" min="0" step="0.01" value={line.credit || ''} onChange={e => updateLine(line.id, 'credit', parseFloat(e.target.value) || 0)} style={{ textAlign: 'right' }} disabled={isReadOnly} /></td>
                    {!isReadOnly && <td><button type="button" className="remove-btn" onClick={() => removeLine(line.id)}><Trash2 size={16} /></button></td>}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {!isReadOnly && (
            <button type="button" className="line-item-add" onClick={() => addLine({ accountId: '', debit: 0, credit: 0 })}><Plus size={16} /> Add line</button>
          )}

          {!isReadOnly && (
            <div className="form-actions">
              <button type="button" className="btn btn-secondary" onClick={() => navigate('/accounting/entries')}>Cancel</button>
              <button type="submit" className="btn btn-secondary">Save Draft</button>
              <button type="button" className="btn btn-primary" disabled={!totals.isBalanced} onClick={handlePost}>
                <Check size={16} /> Post Entry
              </button>
            </div>
          )}
        </form>
      </div></div>
    </>
  );
}
