export const ORDER_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  BILLED: 'BILLED',
  INVOICED: 'INVOICED',
  CANCELLED: 'CANCELLED',
};

export const BILL_INVOICE_STATUSES = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED',
  PAID: 'PAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  CANCELLED: 'CANCELLED',
};

export const JOURNAL_ENTRY_STATUSES = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED',
};

export const BUDGET_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  REVISED: 'REVISED',
  CANCELLED: 'CANCELLED',
};

export const CONTACT_TYPES = {
  CUSTOMER: 'CUSTOMER',
  VENDOR: 'VENDOR',
  BOTH: 'BOTH',
};

export const PRODUCT_TYPES = {
  GOODS: 'GOODS',
  SERVICE: 'SERVICE',
  COMBO: 'COMBO',
};

export const ACCOUNT_TYPES = {
  ASSET: 'ASSET',
  LIABILITY: 'LIABILITY',
  EQUITY: 'EQUITY',
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
};

export const JOURNAL_TYPES = {
  SALES: 'SALES',
  PURCHASE: 'PURCHASE',
  BANK: 'BANK',
  CASH: 'CASH',
  GENERAL: 'GENERAL',
};
