export const DOC_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
};

export const BILL_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
};

export const ENTRY_STATUSES = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED',
};

export const BUDGET_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  REVISED: 'REVISED',
  CANCELLED: 'CANCELLED',
};

export const PRODUCT_TYPES = {
  GOODS: 'GOODS',
  SERVICE: 'SERVICE',
  COMBO: 'COMBO',
};

export const ACCOUNT_TYPES = {
  ASSET: 'ASSET',
  LIABILITY: 'LIABILITY',
  BANK: 'BANK',
  CASH: 'CASH',
  CAPITAL: 'CAPITAL',
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  OTHER_EXPENSE: 'OTHER_EXPENSE',
};

export const JOURNAL_TYPES = {
  SALES: 'SALES',
  PURCHASE: 'PURCHASE',
  BANK: 'BANK',
  CASH: 'CASH',
};

export const ANALYTIC_TYPES = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
};

export const PAYMENT_METHODS = {
  CASH: 'CASH',
  BANK: 'BANK',
};
